### ISSUE TITLE
Not able to convert/fetch all jobs from a URL 

### ISSUE THREAD

**Issue by vivekhash** [ktdreyer/jenkins-job-wrecker#18]
I am using below command to  translate every job on the server on a bash shell - 

`export JJW_USERNAME=*** ; JJW_PASSWORD=*** ; jjwrecker -s http://localhost:8080/`

Ending up with the below error - 

`  File "/home/ubuntu/venv/bin/jjwrecker", line 9, in <module>
    load_entry_point('jenkins-job-wrecker==1.0.6', 'console_scripts', 'jjwrecker')()
  File "/home/ubuntu/jenkins-job-wrecker/jenkins_job_wrecker/cli.py", line 216, in main
    if job['name'] in args.ignore:
TypeError: argument of type 'NoneType' is not iterable
`

I have used python virtual env to set up jjwrecker & environment variables looks fine using "env" command . 
Is it expecting a job name as an argument which it should not as per document?

**Comment by malcolm-brooks** [comment]
Given that you are getting a type of `NoneType' my first guess (I haven't tested anything, just looked in the source) it might be that you are failing because of this:
`
    # Options:
    # -f and -n
    # -s and -n
    **# TODO: -s (without -n means "all jobs on the server")**
`
This seems to suggest that you must (for now) explicitly set the job name you wish to convert from the server. Would you agree? 
Getting it to iterate through all the jobs on the server when -n is not specified shouldn't be a very hard thing TODO though so I might have a look at fixing it when I have some time.

**Comment by vivekhash** [comment]
Thanks for your help Malcolm !
Hoping to get this fixed soon . Reason being we have multiple jenkins master & we want both masters to have same set of jobs ( due to implementation of gearman ) . 

As per ReadMe we should be able to translate all the jobs using only "-s" , I am able to get yaml from the URL using "-n"  , 

`jjwrecker -s http://localhost:8080/ -n 'job2'`

**Comment by kjdowney** [comment]
I was able to work around this is through use of the `-i` parameter and specifying something that I knew wouldn't be a job name.

Example: `jjwrecker -s http://localhost:8080/ -i CATCH_EM_ALL`

If you call with `-s` but without the `-n` option, Jenkins Job Wrecker's behavior is currently set to figure out the list of all jobs on the server, then try to process them all with the exception of whatever you've specified with `-i`.
